### ISSUE TITLE
EDIT: Cannot use Pyrubberband, see comments  |||||||||||||| Move pitch shifting from librosa to pyrubberband

### ISSUE THREAD

**Issue by Leofltt** [TheSoundOfAIOSR/rg_production#8]
Please re implement pitch shifting with pyrubberband and see if you can figure out methods to improve on resampling and do amplitude normalization

**Comment by kanido386** [comment]
Below commits finish this part:
[Use pyrubberband as pitch shifting module](https://github.com/TheSoundOfAIOSR/rg_production/commit/602e25431e2f9d66f7a894bf0067f65d6f56ed74)
[Normalize the samples after pitch shifting](https://github.com/TheSoundOfAIOSR/rg_production/commit/2ea82fe52e1ee4a9f9109857b898a5e05b3116b5)

**Comment by atjessehill** [comment]
Unfortunately Pyrubberband will be difficult to integrate into our project because of the difficulty installing on Windows. After `pip install pyrubberband` on Windows, any call to pyrubberband is met with `RuntimeError: Failed to execute rubberband. Please verify that rubberband-cli is installed`. Getting rubberband-cli installed on Windows is a hassle that looks something like this:
![image](https://user-images.githubusercontent.com/23248106/111482954-c0dc0700-870a-11eb-93ec-d511eee6f244.png)

**Comment by atjessehill** [comment]
Our Librosa issues only happen on Windows during the calls to `Librosa.resample` or `Librosa.pitch_shift`. and is met with a crash that says `Process finished with exit code -1073741819 (0xC0000005)`

The strange thing is this crash only happens when we run our pitch shifting and resampling code as a call from the async thread that runs our GUI. Running it as a standalone thread works as expected.

**Comment by Leofltt** [comment]
I'm linking the bug from librosa related to this issue. Let's not use pyrubberband, sorry Tim!

https://github.com/librosa/librosa/issues/1260

If someone can figure it out from this issue good, otherwise we will have to find a different solution!

**Comment by am1tyadav** [comment]
I'm also using conda and librosa and installing libsndfile solves this issue for me: `conda install -c conda-forge libsndfile` 
I hope this helps!
